import json
import os

def enrich():
    cat_file = os.path.join(os.path.dirname(__file__), 'products.json')
    with open(cat_file, 'r', encoding='utf-8') as f:
        items = json.load(f)

    existing_ids = {it['id'] for it in items}
    new_items = [
        {'id': 'prod_000120', 'sku': 'NOVA-DAIR-AMUL-0120', 'name': 'Amul Masti Dahi Curd 400 g', 'title': 'Amul Masti Dahi Curd 400 g', 'brand': 'Amul', 'category': 'Milk & Dairy', 'subcategory': 'Curd & Dahi', 'price': 35, 'mrp': 38, 'currency': 'INR', 'unit': 'pack', 'pack_size': '400 g', 'availability': 'IN_STOCK', 'tags': ['dairy', 'curd', 'staple'], 'preferred': True, 'imageUrl': None},
        {'id': 'prod_000121', 'sku': 'NOVA-DAIR-AMUL-0121', 'name': 'Amul Fresh Paneer 200 g', 'title': 'Amul Fresh Paneer 200 g', 'brand': 'Amul', 'category': 'Milk & Dairy', 'subcategory': 'Paneer', 'price': 92, 'mrp': 98, 'currency': 'INR', 'unit': 'pack', 'pack_size': '200 g', 'availability': 'IN_STOCK', 'tags': ['dairy', 'paneer'], 'preferred': True, 'imageUrl': None},
        {'id': 'prod_000122', 'sku': 'NOVA-DAIR-AMUL-0122', 'name': 'Amul Pasteurised Butter 100 g', 'title': 'Amul Pasteurised Butter 100 g', 'brand': 'Amul', 'category': 'Milk & Dairy', 'subcategory': 'Butter', 'price': 58, 'mrp': 60, 'currency': 'INR', 'unit': 'pack', 'pack_size': '100 g', 'availability': 'IN_STOCK', 'tags': ['dairy', 'butter'], 'preferred': True, 'imageUrl': None},
        {'id': 'prod_000123', 'sku': 'NOVA-DAIR-AMUL-0123', 'name': 'Amul Processed Cheese Blocks 200 g', 'title': 'Amul Processed Cheese Blocks 200 g', 'brand': 'Amul', 'category': 'Milk & Dairy', 'subcategory': 'Cheese', 'price': 145, 'mrp': 155, 'currency': 'INR', 'unit': 'pack', 'pack_size': '200 g', 'availability': 'IN_STOCK', 'tags': ['dairy', 'cheese'], 'preferred': False, 'imageUrl': None},
        {'id': 'prod_000124', 'sku': 'NOVA-ATTA-FORT-0124', 'name': 'Fortune Chakki Fresh Atta 5 kg', 'title': 'Fortune Chakki Fresh Atta 5 kg', 'brand': 'Fortune', 'category': 'Atta & Rice', 'subcategory': 'Atta & Flour', 'price': 245, 'mrp': 275, 'currency': 'INR', 'unit': 'pack', 'pack_size': '5 kg', 'availability': 'IN_STOCK', 'tags': ['atta', 'staple', 'deal'], 'preferred': False, 'imageUrl': None},
        {'id': 'prod_000125', 'sku': 'NOVA-GRAI-TATA-0125', 'name': 'Tata Sampann Thick Poha 500 g', 'title': 'Tata Sampann Thick Poha 500 g', 'brand': 'Tata Sampann', 'category': 'Atta & Rice', 'subcategory': 'Poha', 'price': 55, 'mrp': 62, 'currency': 'INR', 'unit': 'pack', 'pack_size': '500 g', 'availability': 'IN_STOCK', 'tags': ['poha', 'breakfast'], 'preferred': True, 'imageUrl': None},
        {'id': 'prod_000126', 'sku': 'NOVA-GRAI-FORT-0126', 'name': 'Fortune Sooji / Suji Rava 500 g', 'title': 'Fortune Sooji / Suji Rava 500 g', 'brand': 'Fortune', 'category': 'Atta & Rice', 'subcategory': 'Suji & Rava', 'price': 42, 'mrp': 48, 'currency': 'INR', 'unit': 'pack', 'pack_size': '500 g', 'availability': 'IN_STOCK', 'tags': ['suji', 'staple'], 'preferred': True, 'imageUrl': None},
        {'id': 'prod_000127', 'sku': 'NOVA-OILS-FORT-0127', 'name': 'Fortune Pure Groundnut Oil 1 L', 'title': 'Fortune Pure Groundnut Oil 1 L', 'brand': 'Fortune', 'category': 'Cooking Oils', 'subcategory': 'Groundnut Oil', 'price': 195, 'mrp': 220, 'currency': 'INR', 'unit': 'bottle', 'pack_size': '1 L', 'availability': 'IN_STOCK', 'tags': ['oil', 'groundnut_oil'], 'preferred': False, 'imageUrl': None},
        {'id': 'prod_000128', 'sku': 'NOVA-OILS-GEMI-0128', 'name': 'Gemini Refined Sunflower Oil 1 L', 'title': 'Gemini Refined Sunflower Oil 1 L', 'brand': 'Gemini', 'category': 'Cooking Oils', 'subcategory': 'Sunflower Oil', 'price': 135, 'mrp': 155, 'currency': 'INR', 'unit': 'pouch', 'pack_size': '1 L', 'availability': 'IN_STOCK', 'tags': ['oil', 'sunflower_oil', 'deal'], 'preferred': True, 'imageUrl': None},
        {'id': 'prod_000129', 'sku': 'NOVA-TEAS-TAJM-0129', 'name': 'Brooke Bond Taj Mahal Tea 500 g', 'title': 'Brooke Bond Taj Mahal Tea 500 g', 'brand': 'Taj Mahal', 'category': 'Tea & Staples', 'subcategory': 'Tea', 'price': 340, 'mrp': 380, 'currency': 'INR', 'unit': 'pack', 'pack_size': '500 g', 'availability': 'IN_STOCK', 'tags': ['tea', 'premium_tea'], 'preferred': True, 'imageUrl': None},
        {'id': 'prod_000130', 'sku': 'NOVA-NOOD-NISS-0130', 'name': 'Nissin Cup Noodles Veggie Manchow 70 g', 'title': 'Nissin Cup Noodles Veggie Manchow 70 g', 'brand': 'Nissin', 'category': 'Instant Noodles', 'subcategory': 'Cup Noodles', 'price': 50, 'mrp': 55, 'currency': 'INR', 'unit': 'cup', 'pack_size': '70 g', 'availability': 'IN_STOCK', 'tags': ['noodles', 'cup_noodles'], 'preferred': False, 'imageUrl': None},
        {'id': 'prod_000131', 'sku': 'NOVA-NOOD-MAGG-0131', 'name': 'Maggi Veg Atta Noodles 290 g', 'title': 'Maggi Veg Atta Noodles 290 g', 'brand': 'Maggi', 'category': 'Instant Noodles', 'subcategory': 'Instant Noodles', 'price': 110, 'mrp': 120, 'currency': 'INR', 'unit': 'pack', 'pack_size': '290 g', 'availability': 'IN_STOCK', 'tags': ['maggi', 'atta_noodles'], 'preferred': True, 'imageUrl': None},
        {'id': 'prod_000132', 'sku': 'NOVA-SNAK-PARL-0132', 'name': 'Parle Hide & Seek Chocolate Chip Cookies 120 g', 'title': 'Parle Hide & Seek Chocolate Chip Cookies 120 g', 'brand': 'Parle', 'category': 'Snacks & Biscuits', 'subcategory': 'Biscuits & Cookies', 'price': 40, 'mrp': 45, 'currency': 'INR', 'unit': 'pack', 'pack_size': '120 g', 'availability': 'IN_STOCK', 'tags': ['biscuits', 'cookies', 'chocolate'], 'preferred': True, 'imageUrl': None},
        {'id': 'prod_000133', 'sku': 'NOVA-SNAK-BRIT-0133', 'name': 'Britannia Marie Gold Biscuits 250 g', 'title': 'Britannia Marie Gold Biscuits 250 g', 'brand': 'Britannia', 'category': 'Snacks & Biscuits', 'subcategory': 'Biscuits & Cookies', 'price': 38, 'mrp': 42, 'currency': 'INR', 'unit': 'pack', 'pack_size': '250 g', 'availability': 'IN_STOCK', 'tags': ['biscuits', 'tea_time'], 'preferred': True, 'imageUrl': None},
        {'id': 'prod_000134', 'sku': 'NOVA-SNAK-LAYS-0134', 'name': "Lay's Classic Salted Potato Chips 50 g", 'title': "Lay's Classic Salted Potato Chips 50 g", 'brand': "Lay's", 'category': 'Snacks & Biscuits', 'subcategory': 'Chips & Namkeen', 'price': 20, 'mrp': 20, 'currency': 'INR', 'unit': 'pack', 'pack_size': '50 g', 'availability': 'IN_STOCK', 'tags': ['chips', 'snacks'], 'preferred': True, 'imageUrl': None},
        {'id': 'prod_000135', 'sku': 'NOVA-SNAK-BING-0135', 'name': 'Bingo Mad Angles Achaari Masti 66 g', 'title': 'Bingo Mad Angles Achaari Masti 66 g', 'brand': 'Bingo', 'category': 'Snacks & Biscuits', 'subcategory': 'Chips & Namkeen', 'price': 20, 'mrp': 20, 'currency': 'INR', 'unit': 'pack', 'pack_size': '66 g', 'availability': 'IN_STOCK', 'tags': ['chips', 'namkeen'], 'preferred': False, 'imageUrl': None},
        {'id': 'prod_000136', 'sku': 'NOVA-BEVG-PEPS-0136', 'name': 'Pepsi Cola Soft Drink 750 ml', 'title': 'Pepsi Cola Soft Drink 750 ml', 'brand': 'Pepsi', 'category': 'Beverages', 'subcategory': 'Cold Drinks & Soda', 'price': 40, 'mrp': 40, 'currency': 'INR', 'unit': 'bottle', 'pack_size': '750 ml', 'availability': 'IN_STOCK', 'tags': ['beverages', 'cold_drinks'], 'preferred': True, 'imageUrl': None},
        {'id': 'prod_000137', 'sku': 'NOVA-BEVG-SPRI-0137', 'name': 'Sprite Lime Flavoured Cold Drink 750 ml', 'title': 'Sprite Lime Flavoured Cold Drink 750 ml', 'brand': 'Sprite', 'category': 'Beverages', 'subcategory': 'Cold Drinks & Soda', 'price': 40, 'mrp': 40, 'currency': 'INR', 'unit': 'bottle', 'pack_size': '750 ml', 'availability': 'IN_STOCK', 'tags': ['beverages', 'cold_drinks'], 'preferred': True, 'imageUrl': None},
        {'id': 'prod_000138', 'sku': 'NOVA-BEVG-FROO-0138', 'name': 'Frooti Fresh Mango Drink 1 L', 'title': 'Frooti Fresh Mango Drink 1 L', 'brand': 'Frooti', 'category': 'Beverages', 'subcategory': 'Fruit Juices', 'price': 70, 'mrp': 75, 'currency': 'INR', 'unit': 'pack', 'pack_size': '1 L', 'availability': 'IN_STOCK', 'tags': ['beverages', 'juice'], 'preferred': True, 'imageUrl': None},
        {'id': 'prod_000139', 'sku': 'NOVA-BEVG-PAPB-0139', 'name': 'Paper Boat Aamras Mango Fruit Juice 200 ml', 'title': 'Paper Boat Aamras Mango Fruit Juice 200 ml', 'brand': 'Paper Boat', 'category': 'Beverages', 'subcategory': 'Fruit Juices', 'price': 35, 'mrp': 35, 'currency': 'INR', 'unit': 'pack', 'pack_size': '200 ml', 'availability': 'IN_STOCK', 'tags': ['beverages', 'juice'], 'preferred': False, 'imageUrl': None},
        {'id': 'prod_000140', 'sku': 'NOVA-BEVG-STIN-0140', 'name': 'Sting Energy Drink 250 ml', 'title': 'Sting Energy Drink 250 ml', 'brand': 'Sting', 'category': 'Beverages', 'subcategory': 'Energy Drinks', 'price': 20, 'mrp': 20, 'currency': 'INR', 'unit': 'bottle', 'pack_size': '250 ml', 'availability': 'IN_STOCK', 'tags': ['beverages', 'energy_drink'], 'preferred': False, 'imageUrl': None},
        {'id': 'prod_000141', 'sku': 'NOVA-CLEN-TIDE-0141', 'name': 'Tide Plus Extra Power Detergent Powder 1 kg', 'title': 'Tide Plus Extra Power Detergent Powder 1 kg', 'brand': 'Tide', 'category': 'Cleaning & Toiletries', 'subcategory': 'Detergent & Laundry', 'price': 130, 'mrp': 145, 'currency': 'INR', 'unit': 'pack', 'pack_size': '1 kg', 'availability': 'IN_STOCK', 'tags': ['cleaning', 'detergent', 'laundry'], 'preferred': True, 'imageUrl': None},
        {'id': 'prod_000142', 'sku': 'NOVA-CLEN-COLI-0142', 'name': 'Colin Glass and Surface Cleaner 500 ml', 'title': 'Colin Glass and Surface Cleaner 500 ml', 'brand': 'Colin', 'category': 'Cleaning & Toiletries', 'subcategory': 'Floor & Surface Cleaners', 'price': 105, 'mrp': 115, 'currency': 'INR', 'unit': 'bottle', 'pack_size': '500 ml', 'availability': 'IN_STOCK', 'tags': ['cleaning', 'glass_cleaner'], 'preferred': True, 'imageUrl': None},
        {'id': 'prod_000143', 'sku': 'NOVA-CLEN-COMF-0143', 'name': 'Comfort After Wash Fabric Conditioner Morning Fresh 860 ml', 'title': 'Comfort After Wash Fabric Conditioner Morning Fresh 860 ml', 'brand': 'Comfort', 'category': 'Cleaning & Toiletries', 'subcategory': 'Detergent & Laundry', 'price': 225, 'mrp': 250, 'currency': 'INR', 'unit': 'bottle', 'pack_size': '860 ml', 'availability': 'IN_STOCK', 'tags': ['cleaning', 'fabric_conditioner'], 'preferred': True, 'imageUrl': None}
    ]

    added = 0
    for ni in new_items:
        if ni['id'] not in existing_ids:
            items.append(ni)
            existing_ids.add(ni['id'])
            added += 1

    with open(cat_file, 'w', encoding='utf-8') as f:
        json.dump(items, f, indent=2)

    print(f'Successfully added {added} new unique products! Total in products.json: {len(items)}')

if __name__ == '__main__':
    enrich()
